# Generated by Django 4.0.2 on 2022-06-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=264),
        ),
    ]
